version: "3.7"

services:
  web:
    container_name: transprop_web
    build: ./
    volumes:
      - ./:/app/
      - static_volume:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
  database:
    container_name: transprop_database
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=djdockerdb
      - POSTGRES_USER=djbaron
      - POSTGRES_PASSWORD=icodepython
    volumes:
      - ./database_data:/var/lib/postgresql/data/
  nginx:
    container_name: transprop_nginx
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  database_data:
  static_volume:
  media_volume:
